Traceback (most recent call last):
  File "C:\Users\jkgv1\.conda\envs\Ubidots\lib\site-packages\jupyter_cache\executors\utils.py", line 51, in single_nb_execution
    executenb(
  File "C:\Users\jkgv1\.conda\envs\Ubidots\lib\site-packages\nbclient\client.py", line 1204, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "C:\Users\jkgv1\.conda\envs\Ubidots\lib\site-packages\nbclient\util.py", line 84, in wrapped
    return just_run(coro(*args, **kwargs))
  File "C:\Users\jkgv1\.conda\envs\Ubidots\lib\site-packages\nbclient\util.py", line 62, in just_run
    return loop.run_until_complete(coro)
  File "C:\Users\jkgv1\.conda\envs\Ubidots\lib\asyncio\base_events.py", line 647, in run_until_complete
    return future.result()
  File "C:\Users\jkgv1\.conda\envs\Ubidots\lib\site-packages\nbclient\client.py", line 663, in async_execute
    await self.async_execute_cell(
  File "C:\Users\jkgv1\.conda\envs\Ubidots\lib\site-packages\nbclient\client.py", line 965, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "C:\Users\jkgv1\.conda\envs\Ubidots\lib\site-packages\nbclient\client.py", line 862, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
cargas_grouped = cargas_month['value'].sum()
consumo_otros =  consumo_sede -cargas_grouped 
consumo_otros

piechart_df = cargas_month[["value","variable"]].copy()
piechart_df.loc[-1] = [consumo_otros, "Otros"]
piechart_df.reset_index(inplace=True, drop=True)
piechart_df['value'] = piechart_df['value'].round(decimals = 2)


fig1, ax1 = plt.subplots()
ax1.pie(piechart_df["value"],  labels=piechart_df["variable"], autopct='%1.1f%%',
        shadow=True, startangle=90)
ax1.axis('equal')  # Equal aspect ratio ensures that pie is drawn as a circle.
plt.show()


piechart_df
------------------

[1;31m---------------------------------------------------------------------------[0m
[1;31mValueError[0m                                Traceback (most recent call last)
Input [1;32mIn [10][0m, in [0;36m<cell line: 12>[1;34m()[0m
[0;32m      8[0m piechart_df[[38;5;124m'[39m[38;5;124mvalue[39m[38;5;124m'[39m] [38;5;241m=[39m piechart_df[[38;5;124m'[39m[38;5;124mvalue[39m[38;5;124m'[39m][38;5;241m.[39mround(decimals [38;5;241m=[39m [38;5;241m2[39m)
[0;32m     11[0m fig1, ax1 [38;5;241m=[39m plt[38;5;241m.[39msubplots()
[1;32m---> 12[0m [43max1[49m[38;5;241;43m.[39;49m[43mpie[49m[43m([49m[43mpiechart_df[49m[43m[[49m[38;5;124;43m"[39;49m[38;5;124;43mvalue[39;49m[38;5;124;43m"[39;49m[43m][49m[43m,[49m[43m  [49m[43mlabels[49m[38;5;241;43m=[39;49m[43mpiechart_df[49m[43m[[49m[38;5;124;43m"[39;49m[38;5;124;43mvariable[39;49m[38;5;124;43m"[39;49m[43m][49m[43m,[49m[43m [49m[43mautopct[49m[38;5;241;43m=[39;49m[38;5;124;43m'[39;49m[38;5;132;43;01m%1.1f[39;49;00m[38;5;132;43;01m%%[39;49;00m[38;5;124;43m'[39;49m[43m,[49m
[0;32m     13[0m [43m        [49m[43mshadow[49m[38;5;241;43m=[39;49m[38;5;28;43;01mTrue[39;49;00m[43m,[49m[43m [49m[43mstartangle[49m[38;5;241;43m=[39;49m[38;5;241;43m90[39;49m[43m)[49m
[0;32m     14[0m ax1[38;5;241m.[39maxis([38;5;124m'[39m[38;5;124mequal[39m[38;5;124m'[39m)  [38;5;66;03m# Equal aspect ratio ensures that pie is drawn as a circle.[39;00m
[0;32m     15[0m plt[38;5;241m.[39mshow()

File [1;32m~\.conda\envs\Ubidots\lib\site-packages\matplotlib\__init__.py:1412[0m, in [0;36m_preprocess_data.<locals>.inner[1;34m(ax, data, *args, **kwargs)[0m
[0;32m   1409[0m [38;5;129m@functools[39m[38;5;241m.[39mwraps(func)
[0;32m   1410[0m [38;5;28;01mdef[39;00m [38;5;21minner[39m(ax, [38;5;241m*[39margs, data[38;5;241m=[39m[38;5;28;01mNone[39;00m, [38;5;241m*[39m[38;5;241m*[39mkwargs):
[0;32m   1411[0m     [38;5;28;01mif[39;00m data [38;5;129;01mis[39;00m [38;5;28;01mNone[39;00m:
[1;32m-> 1412[0m         [38;5;28;01mreturn[39;00m func(ax, [38;5;241m*[39m[38;5;28mmap[39m(sanitize_sequence, args), [38;5;241m*[39m[38;5;241m*[39mkwargs)
[0;32m   1414[0m     bound [38;5;241m=[39m new_sig[38;5;241m.[39mbind(ax, [38;5;241m*[39margs, [38;5;241m*[39m[38;5;241m*[39mkwargs)
[0;32m   1415[0m     auto_label [38;5;241m=[39m (bound[38;5;241m.[39marguments[38;5;241m.[39mget(label_namer)
[0;32m   1416[0m                   [38;5;129;01mor[39;00m bound[38;5;241m.[39mkwargs[38;5;241m.[39mget(label_namer))

File [1;32m~\.conda\envs\Ubidots\lib\site-packages\matplotlib\axes\_axes.py:3045[0m, in [0;36mAxes.pie[1;34m(self, x, explode, labels, colors, autopct, pctdistance, shadow, labeldistance, startangle, radius, counterclock, wedgeprops, textprops, center, frame, rotatelabels, normalize)[0m
[0;32m   3042[0m     [38;5;28;01mraise[39;00m [38;5;167;01mValueError[39;00m([38;5;124m"[39m[38;5;124mx must be 1D[39m[38;5;124m"[39m)
[0;32m   3044[0m [38;5;28;01mif[39;00m np[38;5;241m.[39many(x [38;5;241m<[39m [38;5;241m0[39m):
[1;32m-> 3045[0m     [38;5;28;01mraise[39;00m [38;5;167;01mValueError[39;00m([38;5;124m"[39m[38;5;124mWedge sizes [39m[38;5;124m'[39m[38;5;124mx[39m[38;5;124m'[39m[38;5;124m must be non negative values[39m[38;5;124m"[39m)
[0;32m   3047[0m sx [38;5;241m=[39m x[38;5;241m.[39msum()
[0;32m   3049[0m [38;5;28;01mif[39;00m normalize:

[1;31mValueError[0m: Wedge sizes 'x' must be non negative values
ValueError: Wedge sizes 'x' must be non negative values

